apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - name: manager
        command: [ /manager ]
        image: controller
        resources:
          limits: {cpu: 100m, memory: 30Mi}
          requests: {cpu: 100m, memory: 20Mi}
        env:
          - name: CONCOURSE_URL
            value: "http://192.168.0.11:8080"
          - name: CONCOURSE_USERNAME
            valueFrom:
              secretKeyRef:
                name: concourse-auth
                key: username
          - name: CONCOURSE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: concourse-auth
                key: password
      terminationGracePeriodSeconds: 10
