
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-concourse-concourse-ci-org-v1-pipeline
  failurePolicy: Fail
  name: mpipeline.kb.io
  rules:
  - apiGroups:
    - concourse.concourse-ci.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pipelines

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-concourse-concourse-ci-org-v1-pipeline
  failurePolicy: Fail
  name: vpipeline.kb.io
  rules:
  - apiGroups:
    - concourse.concourse-ci.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pipelines
